sudo: required
services:
  - docker

before_install:
  - docker build -t rawatharsh1986/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true rawatharsh1986/react-test npm test

after_success:
  - docker build -t rawatharsh1986/multi-client ./client
  - docker build -t rawatharsh1986/multi-server ./server
  - docker build -t rawatharsh1986/multi-worker ./worker
  - docker build -t rawatharsh1986/multi-nginx ./nginx
  # Log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take those image and push them to docker hub
  - docker push rawatharsh1986/multi-client
  - docker push rawatharsh1986/multi-server
  - docker push rawatharsh1986/multi-worker
  - docker push rawatharsh1986/multi-nginx

deploy:
  provider: elasticbeanstalk
  region: us-east-2
  app: multi-docker
  env: MultiDocker-env
  bucket_name: elasticbeanstalk-us-east-2-191064771283
  bucket_path: docker-multi
  on:
    branch: master
  access_key_id: 
    secure: $AWS_ACCESS_KEY
  secret_access_key:
    secure: $AWS_SECRET_KEY